//! Location context resolution
//!
//! Ported from TypeSpec compiler/src/core/helpers/location-context.ts
//!
//! LocationContext determines the access scope of a source location:
//! - **Compiler**: Standard library definitions bundled with the compiler
//! - **Library**: Third-party library code (imported via `import`)
//! - **Project**: User's own TypeSpec source files
//! - **Synthetic**: Programmatically generated types (no source file)

/// The type of location context for a diagnostic target
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LocationContext {
    /// The target comes from the compiler's standard library
    Compiler,
    /// The target comes from an imported library
    Library,
    /// The target comes from the user's project source files
    Project,
    /// The target is synthetic (generated by the compiler)
    Synthetic,
}

/// Get the location context for a type — simplified version
/// In the TS version, this uses program.getSourceFileLocationContext()
/// which checks the source file's package identity.
/// Our version defaults to Project for user code since we don't yet
/// have a full package resolution system.
pub fn get_location_context(is_synthetic: bool) -> LocationContext {
    if is_synthetic {
        LocationContext::Synthetic
    } else {
        LocationContext::Project
    }
}

/// Check if access from `source` to an internal symbol declared in `target` is allowed.
/// Ported from TS checker.ts checkSymbolAccess.
///
/// Access rules:
/// - Synthetic/Compiler source: always allowed (compiler internals can use other internals)
/// - Project source: only allowed if target is also Project (same project)
/// - Library source: only allowed if target is in the same Library
/// - Cross-scope access to internal symbols is denied
pub fn is_access_allowed(source: &LocationContext, target: &LocationContext) -> bool {
    match source {
        LocationContext::Synthetic | LocationContext::Compiler => true,
        LocationContext::Project => matches!(target, LocationContext::Project),
        LocationContext::Library => matches!(target, LocationContext::Library),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_synthetic_location() {
        assert_eq!(get_location_context(true), LocationContext::Synthetic);
    }

    #[test]
    fn test_source_file_location() {
        assert_eq!(get_location_context(false), LocationContext::Project);
    }

    #[test]
    fn test_access_synthetic_to_anything() {
        assert!(is_access_allowed(
            &LocationContext::Synthetic,
            &LocationContext::Project
        ));
        assert!(is_access_allowed(
            &LocationContext::Synthetic,
            &LocationContext::Library
        ));
        assert!(is_access_allowed(
            &LocationContext::Synthetic,
            &LocationContext::Compiler
        ));
    }

    #[test]
    fn test_access_compiler_to_anything() {
        assert!(is_access_allowed(
            &LocationContext::Compiler,
            &LocationContext::Project
        ));
        assert!(is_access_allowed(
            &LocationContext::Compiler,
            &LocationContext::Library
        ));
    }

    #[test]
    fn test_access_project_to_project() {
        // Same project: internal access allowed
        assert!(is_access_allowed(
            &LocationContext::Project,
            &LocationContext::Project
        ));
        // Cross-scope: Project cannot access Compiler-internal or Library-internal
        assert!(!is_access_allowed(
            &LocationContext::Project,
            &LocationContext::Compiler
        ));
        assert!(!is_access_allowed(
            &LocationContext::Project,
            &LocationContext::Library
        ));
    }

    #[test]
    fn test_access_library_to_library() {
        // Same library: internal access allowed
        assert!(is_access_allowed(
            &LocationContext::Library,
            &LocationContext::Library
        ));
        // Cross-scope: Library cannot access Compiler-internal or Project-internal
        assert!(!is_access_allowed(
            &LocationContext::Library,
            &LocationContext::Compiler
        ));
        assert!(!is_access_allowed(
            &LocationContext::Library,
            &LocationContext::Project
        ));
    }
}
