//! YAML Emitter
//!
//! Emits TypeSpec to OpenAPI YAML format.

use super::emitter::{get_name, get_type_string};
use super::{EmitResult, Emitter};
use crate::ast::types::*;
use crate::parser::{AstBuilder, AstNode, ParseResult};

/// YAML Emitter implementation
pub struct YamlEmitter;

impl YamlEmitter {
    pub fn new() -> Self {
        Self
    }
}

impl Default for YamlEmitter {
    fn default() -> Self {
        Self::new()
    }
}

impl Emitter for YamlEmitter {
    fn emit(&self, result: &ParseResult) -> Result<EmitResult, String> {
        let mut yaml = String::new();

        // Header
        yaml.push_str("# Generated by typespec-rs\n");
        yaml.push_str("# TypeSpec source\n\n");

        // Collect declarations
        let mut models: Vec<String> = Vec::new();
        let mut interfaces: Vec<String> = Vec::new();
        let mut enums: Vec<String> = Vec::new();
        let mut aliases: Vec<String> = Vec::new();

        for node in result.builder.nodes.values() {
            match node {
                AstNode::ModelDeclaration(m) => {
                    let name = get_name(&result.builder, m.name);
                    let model_yaml = self.emit_model(&result.builder, m, &name);
                    models.push(model_yaml);
                }
                AstNode::InterfaceDeclaration(i) => {
                    let name = get_name(&result.builder, i.name);
                    let interface_yaml = self.emit_interface(&result.builder, i, &name);
                    interfaces.push(interface_yaml);
                }
                AstNode::EnumDeclaration(e) => {
                    let name = get_name(&result.builder, e.name);
                    let enum_yaml = self.emit_enum(&result.builder, e, &name);
                    enums.push(enum_yaml);
                }
                AstNode::AliasStatement(a) => {
                    let name = get_name(&result.builder, a.name);
                    aliases.push(name);
                }
                _ => {}
            }
        }

        // Output models
        if !models.is_empty() {
            yaml.push_str("models:\n");
            for model in models {
                yaml.push_str(&model);
            }
            yaml.push('\n');
        }

        // Output interfaces
        if !interfaces.is_empty() {
            yaml.push_str("interfaces:\n");
            for interface in interfaces {
                yaml.push_str(&interface);
            }
            yaml.push('\n');
        }

        // Output enums
        if !enums.is_empty() {
            yaml.push_str("enums:\n");
            for enum_yaml in enums {
                yaml.push_str(&enum_yaml);
            }
            yaml.push('\n');
        }

        // Output aliases
        if !aliases.is_empty() {
            yaml.push_str("aliases:\n");
            for alias in aliases {
                yaml.push_str(&format!("  - {}\n", alias));
            }
        }

        Ok(EmitResult::new(yaml, "yaml", result.diagnostics.len()))
    }

    fn format(&self) -> &str {
        "yaml"
    }
}

impl YamlEmitter {
    fn emit_model(&self, builder: &AstBuilder, model: &ModelDeclaration, name: &str) -> String {
        let mut s = String::new();
        s.push_str(&format!("  {}:\n", name));
        s.push_str("    type: object\n");
        s.push_str("    properties:\n");

        for &prop_id in &model.properties {
            if let Some(AstNode::ModelProperty(prop)) = builder.nodes.get(&prop_id) {
                let prop_name = get_name(builder, prop.name);
                let type_str = get_type_string(builder, prop.value);
                let optional = if prop.optional { "?" } else { "" };
                s.push_str(&format!("      {}{}: {}\n", prop_name, optional, type_str));
            }
        }

        s
    }

    fn emit_interface(
        &self,
        builder: &AstBuilder,
        interface: &InterfaceDeclaration,
        name: &str,
    ) -> String {
        let mut s = String::new();
        s.push_str(&format!("  {}:\n", name));
        s.push_str("    operations:\n");

        for &op_id in &interface.operations {
            if let Some(AstNode::OperationDeclaration(op)) = builder.nodes.get(&op_id) {
                let op_name = get_name(builder, op.name);
                let return_type = if let Some(AstNode::OperationSignatureDeclaration(sig)) =
                    builder.nodes.get(&op.signature)
                {
                    get_type_string(builder, sig.return_type)
                } else {
                    "void".to_string()
                };
                s.push_str(&format!("      {}: {}\n", op_name, return_type));
            }
        }

        s
    }

    fn emit_enum(&self, builder: &AstBuilder, enum_decl: &EnumDeclaration, name: &str) -> String {
        let mut s = String::new();
        s.push_str(&format!("  {}:\n", name));
        s.push_str("    values:\n");

        for &member_id in &enum_decl.members {
            if let Some(AstNode::EnumMember(member)) = builder.nodes.get(&member_id) {
                let member_name = get_name(builder, member.name);
                s.push_str(&format!("      - {}\n", member_name));
            }
        }

        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    #[test]
    fn test_yaml_emitter_model() {
        let src = "model Pet { name: string; }";
        let result = parse(src);
        let emitter = YamlEmitter::new();
        let output = emitter.emit(&result).unwrap();
        assert!(output.output.contains("Pet"));
        assert!(output.output.contains("name"));
        assert_eq!(output.format, "yaml");
    }

    #[test]
    fn test_yaml_emitter_enum() {
        let src = "enum Color { red, green, blue }";
        let result = parse(src);
        let emitter = YamlEmitter::new();
        let output = emitter.emit(&result).unwrap();
        assert!(output.output.contains("Color"));
    }

    #[test]
    fn test_yaml_emitter_interface() {
        let src = "interface Service { read(): string; }";
        let result = parse(src);
        let emitter = YamlEmitter::new();
        let output = emitter.emit(&result).unwrap();
        assert!(output.output.contains("Service"));
    }

    #[test]
    fn test_yaml_emitter_default() {
        let emitter = YamlEmitter;
        let src = "model X {}";
        let result = parse(src);
        let output = emitter.emit(&result).unwrap();
        assert_eq!(output.format, "yaml");
    }
}
